apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubaitodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubaitodo
  template:
    metadata:
      labels:
        app: dubaitodo
    spec:
      containers:
      - name: dubaitodo-container
        image: ghcr.io/alexanderclo22/theapp:8d6107fa29a5253ca4608b3eb3f2778b24520792
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config