apiVersion: v1
kind: Service
metadata:
  name: dubaiowlsapi-service
spec:
  selector:
    app: dubaiowlsapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: {{ .Values.serviceType }}